### ISSUE TITLE
Add ability to edit meta information to images such as alt tag

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v5.2.14#135]
As above

**Comment by havenswift-hosting** [comment]
As this is an enhancement request, can you please move to the V6 issues list

**Comment by abrookbanks** [comment]
This has been done. It takes the product name if no description has been added to the image. I'm not sre its on the alt tag though so may need extra work. 
![screen shot 2015-03-10 at 15 30 28](https://cloud.githubusercontent.com/assets/4520803/6578176/76f797b2-c73a-11e4-9192-c799e236d55f.png)
