### ISSUE TITLE
Show Prices Inc/Ex VAT

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v5.2.14#87]
As above.. add functionality to allow customer to show prices with or without VAT.

**Comment by hairydogltd** [comment]
V6 goes some of the way there. You can set up a Trade customer group for your business customers, then assign them to that group set CubeCart to show prices without VAT to them. You can also give them discounted prices if you like.

But I can see that's not the same as showing inc/exc VAT prices on the page. We have clients who like to do that, though I'm not sure it is always a good idea.

**Comment by havenswift-hosting** [comment]
As this is an enhancement request, can you please move to the V6 issues list.  As I mentioned this is critical for users that sell B2B and B2C - without it, Trading Standards can and have forced websites offline !
